version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:password@db/mydatabase
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data/db:/var/lib/mysql