version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5050:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:password@db/mydatabase
      - SECRET_KEY=secret_key
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: